remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Methodology Assignment 4, Task 2"
description: "Part 2 of DSC180A MA4"
